### ISSUE TITLE
union関数の命名

### ISSUE THREAD

**Issue by yojiyama7** [kaityo256/zenn-content#27]
unionと命名された関数がありますがuniteのほうが適切ではないでしょうか？
(unionは名詞なので関数名らしくないと感じました)

ご検討よろしくお願いします。

https://zenn.dev/kaityo256/articles/programming_howto

**Comment by kaityo256** [comment]
コメントをありがとうございます。unite派、union派がいるようなのですが、例えばWikipediaがUnion派なので、私はUnionを採用しております。C/C++ではunionが予約語なので、unite派がおおいようですね。
https://en.wikipedia.org/wiki/Disjoint-set_data_structure
